version: '3.7'
services:
  mongodb:
    image: mongo:4.4.0-rc10-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - 27017:27017
    volumes:
      - mongodb_container_data:/data/db
volumes:
  mongodb_container_data: